import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const Header = dynamic(() => import('../components/Header'), { ssr: false });
const StairTransition = dynamic(() => import('../components/StairTransition'), { ssr: false });

// Если `PageTransition` тоже использует framer-motion — тоже можно сделать динамическим.
// import PageTransition from "../components/PageTransition";
const PageTransition = dynamic(() => import('../components/PageTransition'), { ssr: false });

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ['100', "200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-jetbrainsMono',
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>
            {children}
        </PageTransition>
        </body>
        </html>
    );
}